# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotime_cn_website', '0004_auto_20170601_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='update/%Y%m%d'),
        ),
    ]
